### ISSUE TITLE
not working for other cik's

### ISSUE THREAD

**Issue by manogna-180030491** [vilasshettigar/secedgar-form13#1]
I tried this code for other cik's
its not  showing anything

**Comment by vilasshettigar** [comment]
Please see what is the output you get from this part of the code:
filings_url_json_text = requests.get(filings_url).text   # Get text from URL
print(filings_url_json_text)  # This is needed. Sometimes, we get an error from the site. Usually it works in 1-2 tries

This is where, the call behaves differently on occasion. Instead of the JSON, it throws an error page. A retry code may be added to not go any further until the JSON is returned.

One approach may be to force the headers, but even that has not behaved consistently for me.
headers = {
    'User-Agent': 'Personal Use youremail@domain.com',
    'Referer': 'https://www.sec.gov/',
    'Accept-Encoding': 'gzip, deflate',
    'Accept': 'application/json',
    'Accept-Language': 'en-US'
}
filings_url_json_text = requests.get(filings_url, headers=headers).text   # Get text from URL

I just tried with a new CIK (1336528 - Bill Ackman's: Pershing Square Capital Management) and it worked fine for me.

**Comment by manogna-180030491** [comment]
I have checked with this approach you have mentioned,

for some cik's its working fine


>>filings_url_json_text = requests.get(filings_url).text 
over here after running it for 2 or 3 times ,the output is fine,after your adding your suggrested snippet,its all good for filings _url_json_text.


>>form13fhr_df['filingDate'] = pd.to_datetime(form13fhr_df['filingDate']) # Gives warning. Convert to datetime for comparison
 over here , for some cik's its not giving any warning,


>>form13fhr_df = form13fhr_df.sort_values(by=['filingDate'], ascending=False)  # Sort for latest filing first
form13fhr_df = form13fhr_df.reset_index(drop=True)   # reseting the index
form13fhr_df.shape      # see how many records are there to be processed
out[23]:(0, 14)----> over here this  is the output being given for many cik's any finally 'complete_list_df' is empty.


please try for cik's:1009652,1035028,1027781

**Comment by vilasshettigar** [comment]
The valid form types are '13F-HR', '13F-HR/A', '13F-NT', and '13F-NT/A'. These are usually filed by fund managers like Berkshire, Gotham etc. The CIKs you have shared are for public companies. They usually file Schedule 13E (SC 13E) which has details of private transactions. This program will not work for it. 

Here are some examples to try (I have not done it for all as yet. So, please report any bugs you discover)
Steven Cohen's: Point72 Asset Management        0001603466
Chase Coleman's: Tiger Global Management        0001167483
Ray Dalio's: Bridgewater Associates            0001350694
Joel Greenblatt's: Gotham Asset Management        0001510387
Carl Icahn: Icahn Carl C                    0000921669
Seth Klarman's: Baupost Group                0001061768
Daniel Loeb's: Third Point                0001040273
George Soros's: Soros Fund Management            0001029160
